### ISSUE TITLE
Duplicate class build error

### ISSUE THREAD

**Issue by sentry0** [vmi/selenese-runner-java#212] opened 2016-09-09 14:49 UTC
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-95-generic", arch: "amd64", family: "unix"
.
.
.
.
.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.061s
[INFO] Finished at: Fri Sep 09 10:43:32 EDT 2016
[INFO] Final Memory: 33M/372M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.2:shade (default) on project selenese-runner-java: Error creating shaded jar: duplicate entry: Main.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.2:shade (default) on project selenese-runner-java: Error creating shaded jar: duplicate entry: Main.class
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar: duplicate entry: Main.class
    at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:539)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: java.util.zip.ZipException: duplicate entry: Main.class
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
    at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
    at org.apache.maven.plugins.shade.resource.IncludeResourceTransformer.modifyOutputStream(IncludeResourceTransformer.java:63)
    at org.apache.maven.plugins.shade.DefaultShader.shade(DefaultShader.java:203)
    at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:454)
    ... 21 more

**Comment by sentry0** [comment] 2016-09-09 15:25
I'm not sure why but it seems like when I comment out the transformer entry on line 123 of the pom.xml it seems to build fine.

Some clarification if I've broken the build and around what this transformers purpose is would be appreciated.

**Comment by sentry0** [comment] 2016-09-09 15:25
I'm not sure why but it seems like when I comment out the transformer entry on line 123 of the pom.xml it seems to build fine.

Some clarification if I've broken the build and around what this transformers purpose is would be appreciated.

**Comment by sentry0** [comment] 2016-09-09 15:25
I'm not sure why but it seems like when I comment out the transformer entry on line 123 of the pom.xml it seems to build fine.

Some clarification if I've broken the build and around what this transformers purpose is would be appreciated.

**Comment by sentry0** [comment] 2016-09-09 15:34
I'm not sure why but it seems like when I comment out the transformer entry on line 123 of the pom.xml it seems to build fine.

Some clarification if I've broken the build and around what this transformers purpose is would be appreciated.

**Comment by vmi** [comment] 2016-09-11 08:49
Hmmm, I could not reproduce your problem.

`mvn -version`
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 22:51:28+0900)
Maven home: /home/vmi/opt/maven
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_102/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-85-generic", arch: "amd64", family: "unix"


`mvn -P package` is terminated normally.

**Comment by sentry0** [comment] 2016-09-13 15:36
It may be related to this note in your documentation:

"Top-level Main class is contained ONLY in stand-alone "selenese-runner.jar", and is not contained in "selenese-runner-java-X.Y.Z.jar" in maven repository. Please use "jp.vmi.selenium.selenese.Main" instead of "Main" if you want to use this feature with the jar in maven repository."

**Comment by vmi** [comment] 2016-09-13 22:42
Please run following commands and attach `build.log.gz`.

```
mvn clean
script -c 'mvn -X -P package' build.log
gzip build.log
```

**Comment by vmi** [comment] 2017-01-07 02:45
Hi,

Is your problem solved?
If you solve it, please close this issue.
If you do not solve it, please attach the above information.

**Closed** 2017-02-07 21:23 UTC
Labels: pending, question, want more info
