### ISSUE TITLE
verify text with line break fails in selenese-runner, works in IDE

### ISSUE THREAD

**Issue by katii** [vmi/selenese-runner-java#164] opened 2015-08-12 07:28 UTC
I have a bootstrap dialog message with two lines of text i.e. line break between the two lines. I want to verify the text with my test srcipt. 

This works in Selenium IDE 2.9.0: 
verifyText | class=bootstrap-dialog-message | Delete selected? \nselenium_testi
[info] Executing: |verifyText | class=bootstrap-dialog-message | Delete selected? selenium_testi | 

But selenese-runner gives me this error to the test report:
verifyText	class=bootstrap-dialog-message	Delete selected? 
selenium_testi	
[Warning: Assertion failed (Result: [Delete selected? selenium_testi] / Expected: [Delete selected? selenium_testi])]

And the command prompt shows:
[ERROR] Command#31: verifyText("class=bootstrap-dialog-message", "Delete selected?
selenium_testi") => [Warning: Assertion failed (Result: [Delete selected?
selenium_testi] / Expected: [Delete selected?
selenium_testi])]

Selenese Runner Version:	1.11.0
WebDriver Name:	InternetExplorerDriver
Selenium Version:	2.46.0
Java Version:	1.8.0_45
Java VM Name:	Java HotSpot(TM) 64-Bit Server VM
Operating System:	Windows 8.1 6.3 (amd64)

**Comment by vmi** [comment] 2015-08-13 22:40
Hi,

Hmmm, I cannot reproduce your problem.
Can you provide minimal HTML and test case?

**Comment by vmi** [comment] 2015-08-25 22:56
Hi,

I cannot reproduce the problem yet.
Please provide more information.

**Comment by vmi** [comment] 2015-09-21 02:29
I think this problem has been resolved by P.R. #166.
Please test it.

**Comment by vmi** [comment] 2015-12-01 23:01
Please re-open this if there is still any problem.

**Closed by vmi** 2015-12-01 23:01 UTC
Labels: bug
